version: "3"
services:
  frontend:
    build:
      context: front
      target: dev
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "9000:5173"
    networks:
      - api
  backend:
    build:
      context: py_backend
    networks:
      - api
    ports:
      - "9100:8080"
networks:
  api:
    driver: bridge