version: "3"
services:
  frontend:
    build:
      context: front
      target: prod
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "9000:80"
    networks:
      - api
  backend:
    build:
      context: backend
    networks:
      - api
    ports:
      - "9100:3000"
networks:
  api:
    driver: bridge